### PR TITLE
Fix #321 UI scale for ultrawide resolution (7680x1440p)

### LINKED ISSUE #321: UI Doesn't Scale Correctly for Ultrawide Resolution (7680x1440p)
## Description
Server browser is squished and "Join" buttons don't work when playing on 7680x1440p resolution. In the 1.0 release, this was not the case. I would consider this a low priority as I understand this resolution is not in widespread use. Please fix other more pressing issues first.

## Steps to reproduce
1. Start the game.
2. Load a save.
3. Open the server browser.

## Reproduction rate
[ X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

## Expected result
For the UI to not be squished and join buttons to work.

## Evidence (optional)
server-menu

### PR DESCRIPTION
**Pull request by Dumbeldor**

### CODE REVIEW

**Comment by Dumbeldor** [comment]
I only have 1080p screens but I was able to reproduce the problem by faking the resolution in firefox.
 It should be fine

**Comment by scomans** [comment]
You can't do that. It will break the virtual scrolling of the list.

**Comment by Dumbeldor** [comment]
Aye @scomans are you sure about that ?
image
It seems ok

**Comment by scomans** [comment]
It will look fine in the middle but every row with more than 38 pixel will result in entries being cut off at the end of the list.

**Comment by Dragonisser** [comment]
Sorry Dumbo :P 
https://github.com/tiltedphoques/TiltedEvolution/pull/318

**Pull request closed without merging**
