### PR TITLE
Cyrillic UI font

### PR DESCRIPTION
**Pull request by Sidiusz**
Adds Cyrillic support to the font
Before the font had "standard windows characters" for Russian letters, I added letters in the style of the original font
Also now you can write in chat in Russian and it does not turn into a "mess" of symbols

### CODE REVIEW

**Comment by croscas** [comment]
Can you update the description explaining why this change is needed and what does it fix?

**Comment by Sidiusz** [comment]
Added

> Can you update the description explaining why this change is needed and what does it fix?

**Comment by Dragonisser** [comment]
Please get rid of every other change than the font. Make a new branch based on the up-to-date **dev** and PR this then.

**Review by Dragonisser — APPROVED** [review]
Can be merged

**Pull request merged**
