### PR TITLE
Add Lua scripting API for the server (WIP)

### PR DESCRIPTION
**Pull request by Pospelove**

### CODE REVIEW

**Comment by Dragonisser** [comment]
Wrong branch -> dev

**Comment by Pospelove** [comment]
> Scripting should be its own component, it shouldn't be a service.
Thanks for taking a look! I'll fix that before marking the PR as "ready for review"

**Comment by Pospelove** [comment]
lololol wasn't able to include some files after making a component, keeping service for now

**Comment by Pospelove** [comment]
closing in favor of #544

**Pull request closed without merging**
