### PR TITLE
ST logo for main menu.

### PR DESCRIPTION
**Pull request by ItIsNotLegend**
Adds the ST logo from Harbor to reborn, will only work if contents of mod is moved one folder forward due to how it is packed.

### CODE REVIEW

**Comment by RobbeBryssinck** [comment]
Top right of the pull request, click "Edit", then merge it into "dev", not "master".

**Comment by ItIsNotLegend** [comment]
> Top right of the pull request, click "Edit", then merge it into "dev", not "master".

fixed, apologies

**Comment by Dragonisser** [comment]
It doesn't need to be moved. The zip that gets generated just need to be adjust so the content would be like this:

- Data
- -SkyrimTogetherReborn
- - -SkyrimTogether.exe
- - -......
- -meshes/interface/logo.nif

**Comment by RobbeBryssinck** [comment]
Yay, more steps to my manual deployment process :p

@ItIsNotLegend Create a "GameFiles\Skyrim\" directory, put the "meshes" folder in there.

**Comment by ItIsNotLegend** [comment]
> Yay, more steps to my manual deployment process :p
> 
> @ItIsNotLegend Create a "GameFiles\Skyrim" directory, put the "meshes" folder in there.

Done, albeit not eloquently

**Comment by cabbagegod** [comment]
> > Yay, more steps to my manual deployment process :p
> > @ItIsNotLegend Create a "GameFiles\Skyrim" directory, put the "meshes" folder in there.
> 
> Done, albeit not eloquently

7754f2b747ff3b7778072a407211ca21742f9885 "whoops" 🤣

**Pull request merged**
